nav_bt:
  ros__parameters:
    active_zone: "zone_b"
    zone_a:
      pt1:
        x: -8.467
        y: -0.545
      pt2:
        x: -7.641
        y: 2.054
      pt3:
        x: -4.615
        y: 1.902
      pt4:
        x: -3.254
        y: -1.070

    zone_b:
      pt1:
        x: -8.481
        y: -2.136
      pt2:
        x: -8.711
        y: -3.803
      pt3:
        x: -3.543
        y: -4.566
      pt4:
        x: -2.800
        y: -3.900

    zone_c:
      pt1:
        x: -5.330
        y: 2.539
      pt2:
        x: 8.443
        y: 2.439
      pt3:
        x: 8.151
        y: -4.382
      pt4:
        x: 5.497
        y: -4.529