nav_bt:
  ros__parameters:
    active_zone: "zone_a"
    zone_a:
      pt1:
        x: -14.936
        y: -2.916
      pt2:
        x: -12.850
        y: -3.166
      pt3:
        x: -15.470
        y: -5.852
      pt4:
        x: -13.008
        y: -5.816

    zone_b:
      pt1:
        x: -21.381
        y: -17.141
      pt2:
        x: -29.114
        y: -16.453
      pt3:
        x: -29.603
        y: -18.222
      pt4:
        x: -21.425
        y: -19.096

    zone_c:
      pt1:
        x: -17.710
        y: -30.990
      pt2:
        x: -15.272
        y: -31.587
      pt3:
        x: -18.072
        y: -33.417
      pt4:
        x: -15.942
        y: -34.115